-- Physician-ready V1 — 83 vendors + 111 vendor_categories (idempotent).
-- Do not seed Other / In-house as vendors.

INSERT INTO public.vendors (slug, display_label)
VALUES
  ('zeiss', 'ZEISS'),
  ('heidelberg_engineering', 'Heidelberg Engineering'),
  ('topcon', 'Topcon'),
  ('optos', 'Optos'),
  ('nidek', 'Nidek'),
  ('oculus', 'OCULUS'),
  ('icare', 'Icare'),
  ('haag_streit', 'Haag-Streit'),
  ('marco', 'Marco'),
  ('olleyes', 'Olleyes'),
  ('virtual_field', 'Virtual Field'),
  ('reichert', 'Reichert'),
  ('keeler', 'Keeler'),
  ('heine', 'HEINE'),
  ('huvitz', 'Huvitz'),
  ('alcon', 'Alcon'),
  ('johnson_and_johnson_vision', 'Johnson & Johnson Vision'),
  ('bausch_plus_lomb', 'Bausch + Lomb'),
  ('oertli', 'Oertli'),
  ('lensar', 'LENSAR'),
  ('ziemer', 'Ziemer'),
  ('rxsight', 'RxSight'),
  ('rayner', 'Rayner'),
  ('hoya_surgical_optics', 'Hoya Surgical Optics'),
  ('staar_surgical', 'STAAR Surgical'),
  ('bvi', 'BVI'),
  ('glaukos', 'Glaukos'),
  ('sight_sciences', 'Sight Sciences'),
  ('new_world_medical', 'New World Medical'),
  ('iantrek', 'Iantrek'),
  ('istar_medical', 'iSTAR Medical'),
  ('nova_eye_medical', 'Nova Eye Medical'),
  ('vialase', 'ViaLase'),
  ('elios_vision', 'Elios Vision'),
  ('abbvie_allergan', 'AbbVie / Allergan'),
  ('iridex', 'Iridex'),
  ('microsurgical_technology', 'MicroSurgical Technology'),
  ('lumenis', 'Lumenis'),
  ('dorc', 'DORC'),
  ('medone_surgical', 'MedOne Surgical'),
  ('norlase', 'Norlase'),
  ('schwind_eye_tech_solutions', 'SCHWIND eye-tech-solutions'),
  ('moria', 'MORIA'),
  ('leica_microsystems', 'Leica Microsystems'),
  ('zumax', 'Zumax'),
  ('designs_for_vision', 'Designs For Vision'),
  ('surgitel', 'Surgitel'),
  ('corza_medical_katena', 'Corza Medical (Katena)'),
  ('mani', 'MANI'),
  ('mastel_surgical', 'Mastel Surgical'),
  ('ior_partners', 'iOR Partners'),
  ('sightpath_medical', 'Sightpath Medical'),
  ('amsurg', 'AMSURG'),
  ('custom_surgical_partners', 'Custom Surgical Partners'),
  ('steris', 'STERIS'),
  ('modmed', 'ModMed'),
  ('nextech', 'Nextech'),
  ('compulink', 'Compulink'),
  ('eyemd_emr', 'EyeMD EMR'),
  ('nextgen_healthcare', 'NextGen Healthcare'),
  ('eclinicalworks', 'eClinicalWorks'),
  ('first_insight_maximeyes', 'First Insight (MaximEyes)'),
  ('ehnote', 'EHNOTE'),
  ('epic', 'Epic'),
  ('encoda', 'Encoda'),
  ('waystar', 'Waystar'),
  ('coronis_health', 'Coronis Health'),
  ('assembly_health', 'Assembly Health'),
  ('whitespace_health', 'Whitespace Health'),
  ('weave', 'Weave'),
  ('phreesia', 'Phreesia'),
  ('solutionreach', 'Solutionreach'),
  ('vital_interaction', 'Vital Interaction'),
  ('nextpatient', 'NextPatient'),
  ('lumata_health', 'Lumata Health'),
  ('medicus_it', 'Medicus IT'),
  ('dedicated_it', 'Dedicated IT'),
  ('codexit', 'CodexIT'),
  ('mckesson', 'McKesson'),
  ('henry_schein', 'Henry Schein'),
  ('cardinal_health', 'Cardinal Health'),
  ('cencora', 'Cencora'),
  ('nitra', 'Nitra')
ON CONFLICT (slug) DO UPDATE SET
  display_label = EXCLUDED.display_label,
  active = true,
  updated_at = now();

-- Category relationships (sort_order = appearance order within category).
INSERT INTO public.vendor_categories (vendor_id, category_id, sort_order)
SELECT v.id, c.id, x.sort_order
FROM (VALUES
  ('zeiss', 'diagnostics_imaging', 0),
  ('heidelberg_engineering', 'diagnostics_imaging', 10),
  ('topcon', 'diagnostics_imaging', 20),
  ('optos', 'diagnostics_imaging', 30),
  ('nidek', 'diagnostics_imaging', 40),
  ('oculus', 'diagnostics_imaging', 50),
  ('icare', 'diagnostics_imaging', 60),
  ('haag_streit', 'diagnostics_imaging', 70),
  ('marco', 'diagnostics_imaging', 80),
  ('olleyes', 'diagnostics_imaging', 90),
  ('virtual_field', 'diagnostics_imaging', 100),
  ('reichert', 'clinic_lane_equipment', 0),
  ('keeler', 'clinic_lane_equipment', 10),
  ('heine', 'clinic_lane_equipment', 20),
  ('huvitz', 'clinic_lane_equipment', 30),
  ('marco', 'clinic_lane_equipment', 40),
  ('topcon', 'clinic_lane_equipment', 50),
  ('nidek', 'clinic_lane_equipment', 60),
  ('haag_streit', 'clinic_lane_equipment', 70),
  ('alcon', 'cataract_phaco', 0),
  ('johnson_and_johnson_vision', 'cataract_phaco', 10),
  ('bausch_plus_lomb', 'cataract_phaco', 20),
  ('oertli', 'cataract_phaco', 30),
  ('zeiss', 'cataract_phaco', 40),
  ('lensar', 'cataract_phaco', 50),
  ('ziemer', 'cataract_phaco', 60),
  ('alcon', 'iol_lens_platforms', 0),
  ('johnson_and_johnson_vision', 'iol_lens_platforms', 10),
  ('bausch_plus_lomb', 'iol_lens_platforms', 20),
  ('rxsight', 'iol_lens_platforms', 30),
  ('rayner', 'iol_lens_platforms', 40),
  ('hoya_surgical_optics', 'iol_lens_platforms', 50),
  ('staar_surgical', 'iol_lens_platforms', 60),
  ('bvi', 'iol_lens_platforms', 70),
  ('zeiss', 'iol_lens_platforms', 80),
  ('glaukos', 'glaucoma_migs', 0),
  ('sight_sciences', 'glaucoma_migs', 10),
  ('new_world_medical', 'glaucoma_migs', 20),
  ('iantrek', 'glaucoma_migs', 30),
  ('istar_medical', 'glaucoma_migs', 40),
  ('nova_eye_medical', 'glaucoma_migs', 50),
  ('vialase', 'glaucoma_migs', 60),
  ('elios_vision', 'glaucoma_migs', 70),
  ('alcon', 'glaucoma_migs', 80),
  ('abbvie_allergan', 'glaucoma_migs', 90),
  ('iridex', 'glaucoma_migs', 100),
  ('microsurgical_technology', 'glaucoma_migs', 110),
  ('lumenis', 'glaucoma_migs', 120),
  ('alcon', 'retina', 0),
  ('bausch_plus_lomb', 'retina', 10),
  ('dorc', 'retina', 20),
  ('oertli', 'retina', 30),
  ('medone_surgical', 'retina', 40),
  ('norlase', 'retina', 50),
  ('iridex', 'retina', 60),
  ('zeiss', 'retina', 70),
  ('alcon', 'refractive_surgery', 0),
  ('johnson_and_johnson_vision', 'refractive_surgery', 10),
  ('zeiss', 'refractive_surgery', 20),
  ('ziemer', 'refractive_surgery', 30),
  ('schwind_eye_tech_solutions', 'refractive_surgery', 40),
  ('staar_surgical', 'refractive_surgery', 50),
  ('glaukos', 'refractive_surgery', 60),
  ('moria', 'refractive_surgery', 70),
  ('alcon', 'or_microscopes_visualization', 0),
  ('zeiss', 'or_microscopes_visualization', 10),
  ('leica_microsystems', 'or_microscopes_visualization', 20),
  ('haag_streit', 'or_microscopes_visualization', 30),
  ('zumax', 'or_microscopes_visualization', 40),
  ('designs_for_vision', 'or_microscopes_visualization', 50),
  ('surgitel', 'or_microscopes_visualization', 60),
  ('alcon', 'surgical_instruments_consumables', 0),
  ('bausch_plus_lomb', 'surgical_instruments_consumables', 10),
  ('bvi', 'surgical_instruments_consumables', 20),
  ('corza_medical_katena', 'surgical_instruments_consumables', 30),
  ('mani', 'surgical_instruments_consumables', 40),
  ('moria', 'surgical_instruments_consumables', 50),
  ('mastel_surgical', 'surgical_instruments_consumables', 60),
  ('ior_partners', 'asc_office_based_surgery', 0),
  ('sightpath_medical', 'asc_office_based_surgery', 10),
  ('amsurg', 'asc_office_based_surgery', 20),
  ('custom_surgical_partners', 'asc_office_based_surgery', 30),
  ('steris', 'asc_office_based_surgery', 40),
  ('modmed', 'emr_practice_management', 0),
  ('nextech', 'emr_practice_management', 10),
  ('compulink', 'emr_practice_management', 20),
  ('eyemd_emr', 'emr_practice_management', 30),
  ('nextgen_healthcare', 'emr_practice_management', 40),
  ('eclinicalworks', 'emr_practice_management', 50),
  ('first_insight_maximeyes', 'emr_practice_management', 60),
  ('ehnote', 'emr_practice_management', 70),
  ('epic', 'emr_practice_management', 80),
  ('encoda', 'billing_revenue_cycle', 0),
  ('waystar', 'billing_revenue_cycle', 10),
  ('coronis_health', 'billing_revenue_cycle', 20),
  ('assembly_health', 'billing_revenue_cycle', 30),
  ('whitespace_health', 'billing_revenue_cycle', 40),
  ('weave', 'patient_engagement', 0),
  ('phreesia', 'patient_engagement', 10),
  ('solutionreach', 'patient_engagement', 20),
  ('vital_interaction', 'patient_engagement', 30),
  ('nextpatient', 'patient_engagement', 40),
  ('lumata_health', 'patient_engagement', 50),
  ('medicus_it', 'it_cybersecurity', 0),
  ('dedicated_it', 'it_cybersecurity', 10),
  ('codexit', 'it_cybersecurity', 20),
  ('mckesson', 'supply_materials', 0),
  ('henry_schein', 'supply_materials', 10),
  ('cardinal_health', 'supply_materials', 20),
  ('cencora', 'supply_materials', 30),
  ('nitra', 'supply_materials', 40)
) AS x(vendor_slug, category_slug, sort_order)
JOIN public.vendors v ON v.slug = x.vendor_slug
JOIN public.infrastructure_categories c ON c.slug = x.category_slug
ON CONFLICT (vendor_id, category_id) DO UPDATE SET
  sort_order = EXCLUDED.sort_order;

-- Sanity guards
DO $$
DECLARE
  v_count int;
  r_count int;
BEGIN
  SELECT count(*) INTO v_count FROM public.vendors WHERE active;
  SELECT count(*) INTO r_count FROM public.vendor_categories;
  IF v_count < 83 THEN
    RAISE EXCEPTION 'expected at least 83 vendors, found %', v_count;
  END IF;
  IF r_count < 111 THEN
    RAISE EXCEPTION 'expected at least 111 vendor_categories, found %', r_count;
  END IF;
END $$;
